[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
m_0_pet = "3VHT8cZiJwxiE4s48r6fv7xBccgjPEYGqKmX5DpkWDe3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-registry = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/registry.ts"
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mint.ts"
test = "anchor run test-registry && anchor run test-mint"